/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pack_Test */

#ifndef _Included_com_metaphore_NativeInput
#define _Included_com_metaphore_NativeInput
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pack_Test
 * Method:    performClick
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_metaphore_NativeInput_performClick
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
